name: py37-df
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
    - docopt==0.6.2
    - future==0.18.2
    - imgaug==0.4.0
    - matplotlib==3.3.0
    - numpy==1.19.1
    - opencv-python==4.3.0.36
    - openslide-python==1.1.1
    - pandas==1.1.0
    - pillow==7.2.0
    - scikit-image==0.17.2
    - scikit-learn==0.23.1
    - scipy==1.5.2
    - tensorboard==2.3.0
    - tensorboardx==2.1
    - termcolor==1.1.0
    - torch==1.5.0+cu101
    - torchvision==0.6.0+cu101
    - tqdm==4.48.0
